// 自动生成的侧边栏配置

export default [
  "",
  {
    title: "Deepseek行业资讯",
    collapsable: false,
    children: [
      "DeepSeek“朋友圈”不断扩围：10家国内外云厂商宣布接入",
      "DeepSeek“金融朋友圈” 从“争先”到“恐后”，从“好用”到“用好”",
      "DeepSeek如何搅动AI产业？",
      "DeepSeek宣布涨价！",
      "DeepSeek带飞科大讯飞？",
      "DeepSeek的“服务器繁忙”让所有人抓狂，背后究竟是怎么回事",
      "DeepSeek被封杀了",
      "DeepSeek预测：未来10年，就业前景最好的10个专业",
      "DeepSeek，紧急声明",
      "vivo与荣耀相继接入DeepSeek：AI深度融合引领手机创新潮流",
      "vivo官宣：将深度融合满血版DeepSeek",
      "不在场的DeepSeek，是巴黎AI峰会真正的主角",
      "争先恐后接入DeepSeek的国产手机，它们的自研大模型怎么办？",
      "价值千万美元的“AI.com”，会是谁给DeepSeek公司使用的呢",
      "外资机构看DeepSeek：提振中国股市 机会藏在这些领域",
      "多家车企接入AI大模型DeepSeek 智能汽车再进一步",
      "如何利用DeepSeek翻身？抓住AI红利，普通人也能逆袭的3个方向",
      "日本如何看待Deepseek",
      "深度求索正在物色韩国人工智能人才，展开确保人才的战争",
      "清华大学：普通人如何抓住DeepSeek红利2025",
      "点赞收藏！DeepSeek在GitHub星标量已超OpenAI",
      "爆冷，DeepSeek出局，苹果AI国行版将与阿里合作",
      "看短剧、“交朋友”，DeepSeek挤进中老年社交圈",
      "被DeepSeek刺激到了？文心一言、ChatGPT同时宣布：免费！ ",
      "运营商全面接入DeepSeek意味着什么？",
      "雷军：钦佩DeepSeek取得的成就，每个人可能都要学习AI知识",
    ],
  },
];
