export default [
  "",
  {
    title: "关于DeepSeek",
    collapsable: true,
    children: [
      "关于DeepSeek/DeepSeek 创始团队介绍",
      "关于DeepSeek/DeepSeek 发展历程",
      "关于DeepSeek/什么是 DeepSeek？有什么核心功能？",
    ],
  },
  {
    title: "DeepSeek使用指南",
    collapsable: true,
    children: [
      "DeepSeek使用指南/DeepSeek API 使用指南",
      "DeepSeek使用指南/DeepSeek 多种使用连接方式推荐",
      "DeepSeek使用指南/DeepSeek 本地部署教程",
      "DeepSeek使用指南/如何在iPhone上用语音调用Deepseek",
      "DeepSeek使用指南/官方 DeepSeek R1 满血版使用指南",
      "DeepSeek使用指南/普通人能用DeepSeek做什么？20个实用建议",
      "DeepSeek使用指南/🔥DeepSeek 小白快速上手指南",
      {
        title: "DeepSeek 提问技巧",
        collapsable: true,
        children: [
          "DeepSeek使用指南/DeepSeek 提问技巧/DeepSeek 提示词基本法则",
          "DeepSeek使用指南/DeepSeek 提问技巧/DeepSeek不好用？那是你还不知道这些指令！",
          "DeepSeek使用指南/DeepSeek 提问技巧/吐血整理！DeepSeek神级指令，好用到爆！",
          "DeepSeek使用指南/DeepSeek 提问技巧/普通人也能轻松掌握的 20 个 DeepSeek 高频提示词（2025版）",
        ],
      },
    ],
  },
  {
    title: "DeepSeek应用场景",
    collapsable: true,
    children: [
      {
        title: "DeepSeek + 内容创作",
        collapsable: true,
        children: [
          "DeepSeek应用场景/DeepSeek + 内容创作/3秒让DeepSeek写出爆款小红书",
          "DeepSeek应用场景/DeepSeek + 内容创作/人有多大胆，地有多大产：如何用DeepSeek写长篇小说-虎嗅网",
          "DeepSeek应用场景/DeepSeek + 内容创作/如何利用DeepSeek进行高效内容创作",
          "DeepSeek应用场景/DeepSeek + 内容创作/用DeepSeek做小红书真的太牛了！轻轻松松打造爆款笔记",
          "DeepSeek应用场景/DeepSeek + 内容创作/用DeepSeek写文章？这4个骚操作让你躺平也能出爆款！（含提示词）",
        ],
      },
      {
        title: "DeepSeek + 创意设计",
        collapsable: true,
        children: [
          "DeepSeek应用场景/DeepSeek + 创意设计/DeepSeek一句话搞定修图难题",
          "DeepSeek应用场景/DeepSeek + 创意设计/deepseek+数字人王炸组合使用方法",
          "DeepSeek应用场景/DeepSeek + 创意设计/用 deepseek 做 AI 视频，绝了，和抄作业一样简单！",
          "DeepSeek应用场景/DeepSeek + 创意设计/绝绝子！用deepseek做AI视频，涨粉10W+（附保姆级教程）",
          "DeepSeek应用场景/DeepSeek + 创意设计/这怕是全网最强的 DeepSeek 图片教程吧，赶紧收藏了！",
        ],
      },
      {
        title: "DeepSeek + 办公效率",
        collapsable: true,
        children: [
          "DeepSeek应用场景/DeepSeek + 办公效率/DeepSeek R1 + 个人知识库，直接起飞！",
          "DeepSeek应用场景/DeepSeek + 办公效率/DeepSeek嵌入到Excel，提升10倍工作效率，太牛了！",
          "DeepSeek应用场景/DeepSeek + 办公效率/DeepSeek配合KIMI，自动生成PPT，感觉自己要失业了！",
          "DeepSeek应用场景/DeepSeek + 办公效率/WPS里装上deepseek，简直就是办公神器",
          "DeepSeek应用场景/DeepSeek + 办公效率/利用deepseek建立专属销售知识库",
          "DeepSeek应用场景/DeepSeek + 办公效率/如何用DeepSeek更高效地工作：10个实用技巧",
          "DeepSeek应用场景/DeepSeek + 办公效率/手把手教你在word中接入deepseek，秒生文档材料",
          "DeepSeek应用场景/DeepSeek + 办公效率/法律人保姆级deepseek使用指南（附指令版）",
        ],
      },
      {
        title: "DeepSeek + 理财",
        collapsable: true,
        children: [
          "DeepSeek应用场景/DeepSeek + 理财/普通人如何通过炒股买基金赚到100万？",
          "DeepSeek应用场景/DeepSeek + 理财/用Deepseek回答：如果有100万闲钱，几年内不用，该怎么理财？",
        ],
      },
      {
        title: "DeepSeek + 编程开发",
        collapsable: true,
        children: [
          "DeepSeek应用场景/DeepSeek + 编程开发/DeepSeek接入Python，一般电脑也能飞速跑，确实可以封神了！",
          "DeepSeek应用场景/DeepSeek + 编程开发/DeepSeek装进VSCode，编程非常丝滑！",
          "DeepSeek应用场景/DeepSeek + 编程开发/教你用DeepSeek+Clien，从0到1开发一个APP",
        ],
      },
    ],
  },

  {
    title: "DeepSeek资源汇总",
    collapsable: true,
    children: [
      "DeepSeek资源汇总/DeepSeek 学习资料",
      "DeepSeek资源汇总/DeepSeek 官方链接",
      "DeepSeek资源汇总/DeepSeek 开源项目",
    ],
  },
  {
    title: "DeepSeek技术解析",
    collapsable: true,
    children: [
      {
        title: "DeepSeek 技术分析",
        collapsable: true,
        children: [
          "DeepSeek技术解析/DeepSeek 技术分析/DeepSeek vs. ChatGPT：谁才是真正的王者？",
          "DeepSeek技术解析/DeepSeek 技术分析/DeepSeek 爆火逻辑、行业影响及对未来AI发展的启示",
          "DeepSeek技术解析/DeepSeek 技术分析/DeepSeek-R1 技术全景解析：从原理到实践的“炼金术配方”",
          "DeepSeek技术解析/DeepSeek 技术分析/DeepSeek技术解读：从V3到R1的MoE架构创新",
          "DeepSeek技术解析/DeepSeek 技术分析/DeepSeek最强专业拆解：清交复教授超硬核解读",
          "DeepSeek技术解析/DeepSeek 技术分析/DeepSeek的优势与不足",
          "DeepSeek技术解析/DeepSeek 技术分析/一文详解 DeepSeek 技术架构",
        ],
      },
      {
        title: "DeepSeek 模型训练",
        collapsable: true,
        children: [
          "DeepSeek技术解析/DeepSeek 模型训练/DeepSeek-R1的四个训练阶段",
          "DeepSeek技术解析/DeepSeek 模型训练/DeepSeek-R1的训练流程强化学习（RL）阶段采用了GRPO算法",
          "DeepSeek技术解析/DeepSeek 模型训练/DeepSeek-V3 高效训练关键技术分析",
          "DeepSeek技术解析/DeepSeek 模型训练/DeepSeek华丽文风从何而来？业内人士：训练数据、训练策略和迭代优化缺一不可",
        ],
      },
    ],
  },
  {
    title: "Deepseek行业资讯",
    collapsable: true,
    children: [
      "Deepseek行业资讯/DeepSeek“朋友圈”不断扩围：10家国内外云厂商宣布接入",
      "Deepseek行业资讯/DeepSeek“金融朋友圈” 从“争先”到“恐后”，从“好用”到“用好”",
      "Deepseek行业资讯/DeepSeek如何搅动AI产业？",
      "Deepseek行业资讯/DeepSeek宣布涨价！",
      "Deepseek行业资讯/DeepSeek带飞科大讯飞？",
      "Deepseek行业资讯/DeepSeek的“服务器繁忙”让所有人抓狂，背后究竟是怎么回事",
      "Deepseek行业资讯/DeepSeek被封杀了",
      "Deepseek行业资讯/DeepSeek预测：未来10年，就业前景最好的10个专业",
      "Deepseek行业资讯/DeepSeek，紧急声明",
      "Deepseek行业资讯/vivo与荣耀相继接入DeepSeek：AI深度融合引领手机创新潮流",
      "Deepseek行业资讯/vivo官宣：将深度融合满血版DeepSeek",
      "Deepseek行业资讯/不在场的DeepSeek，是巴黎AI峰会真正的主角",
      "Deepseek行业资讯/争先恐后接入DeepSeek的国产手机，它们的自研大模型怎么办？",
      "Deepseek行业资讯/价值千万美元的“AI.com”，会是谁给DeepSeek公司使用的呢",
      "Deepseek行业资讯/外资机构看DeepSeek：提振中国股市 机会藏在这些领域",
      "Deepseek行业资讯/多家车企接入AI大模型DeepSeek 智能汽车再进一步",
      "Deepseek行业资讯/如何利用DeepSeek翻身？抓住AI红利，普通人也能逆袭的3个方向",
      "Deepseek行业资讯/日本如何看待Deepseek",
      "Deepseek行业资讯/深度求索正在物色韩国人工智能人才，展开确保人才的战争",
      "Deepseek行业资讯/清华大学：普通人如何抓住DeepSeek红利2025",
      "Deepseek行业资讯/点赞收藏！DeepSeek在GitHub星标量已超OpenAI",
      "Deepseek行业资讯/爆冷，DeepSeek出局，苹果AI国行版将与阿里合作",
      "Deepseek行业资讯/看短剧、“交朋友”，DeepSeek挤进中老年社交圈",
      "Deepseek行业资讯/被DeepSeek刺激到了？文心一言、ChatGPT同时宣布：免费！ ",
      "Deepseek行业资讯/运营商全面接入DeepSeek意味着什么？",
      "Deepseek行业资讯/雷军：钦佩DeepSeek取得的成就，每个人可能都要学习AI知识",
    ],
  },
];
